### ISSUE TITLE
Container mgmt tooling

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#133]
Tooling around containers and identities 

more TBD

**Comment by Pishoy** [comment]
can not verify as still an issue with getting a container 

```
JS-NG> dcl = j.clients.docker.new("mydocker_client")                                                                                                     
JS-NG> dcl.run("container_name", image="threefoldtech/js-ng")                                                                                            
<Container: 141a49d7cd>

JS-NG> j.clients.docker.list_all()                                                                                                                       
{'mydocker_client'}


JS-NG> j.clients.docker.get("mydocker_client")                                                                                                           
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 200, in get
    instance = self.find(name)
               │         └ 'mydocker_client'
               └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 122, in find
    instance = getattr(self, name, None)
                       │     └ 'mydocker_client'
                       └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 437, in getter
    instance = factory._create_instance(name, **factory.store.get(name))
               │                        │       │                 └ 'mydocker_client'
               │                        │       └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
               │                        └ 'mydocker_client'
               └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 152, in _create_instance
    instance = self.type(*args, **kwargs)
               │          │       └ {'base_url': None}
               │          └ ()
               └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
TypeError: __init__() got an unexpected keyword argument 'base_url'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 200, in get
    instance = self.find(name)
               │         └ 'mydocker_client'
               └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 122, in find
    instance = getattr(self, name, None)
                       │     └ 'mydocker_client'
                       └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 437, in getter
    instance = factory._create_instance(name, **factory.store.get(name))
               │                        │       │                 └ 'mydocker_client'
               │                        │       └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
               │                        └ 'mydocker_client'
               └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
  File "/root/js-ng/jumpscale/core/base/factory.py", line 152, in _create_instance
    instance = self.type(*args, **kwargs)
               │          │       └ {'base_url': None}
               │          └ ()
               └ <jumpscale.core.base.factory.jumpscaleclientsdockerdockerDockerClient object at 0x7f4b3f1310f0>
TypeError: __init__() got an unexpected keyword argument 'base_url'

__init__() got an unexpected keyword argument 'base_url'
JS-NG> j.clients.docker.get()                                                                                                                                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get() missing 1 required positional argument: 'name'

get() missing 1 required positional argument: 'name'
JS-NG> j.clients.docker.get()                                                                                                                                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get() missing 1 required positional argument: 'name'

get() missing 1 required positional argument: 'name'

```

**Comment by Pishoy** [comment]
js-sdk version 

```
) root@test-bishoy:~/js-sdk# git log -1
commit 2743752a42aff5284723947a3bca5eebd784e330 (HEAD -> development, origin/development, origin/HEAD)
Author: Waleed <waleed.hammam@gmail.com>
Date:   Thu Jun 25 11:58:41 2020 +0200

    fix nginx permission problem

```

**Comment by Pishoy** [comment]
verifed
