### ISSUE TITLE
Configuration Base object failed to set parent

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-ng#292]
stack trace
```
2020-06-08 15:53:55.601 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:144 - error
Traceback (most recent call last):

> File "/home/maged/Code/js-ng/jumpscale/sals/chatflows/chatflows.py", line 137, in wrapper
    getattr(self, step_name)()
            │     └ 'network_reservation'
            └ <network_deploy.NetworkDeploy object at 0x7fb1e41414a8>

  File "/home/maged/Code/js-ng/jumpscale/sals/chatflows/chatflows.py", line 578, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<network_deploy.NetworkDeploy object at 0x7fb1e41414a8>,)
           └ <function NetworkDeploy.network_reservation at 0x7fb1e41eab70>

  File "/home/maged/Code/js-sdk/jumpscale/packages/tfgrid_solutions/chats/network_deploy.py", line 49, in network_reservation
    bot=self,
        └ <network_deploy.NetworkDeploy object at 0x7fb1e41414a8>

  File "/home/maged/Code/js-ng/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 796, in create_network
    network = j.sals.zos.network.create(reservation, ip_range, network_name)
              │                         │            │         └ 'simulator-network'
              │                         │            └ '10.178.0.0/16'
              │                         └ TfgridWorkloadsReservation1(_Base__instance_name=None, _Base__parent=None, __metadata='IC`}9$^Cl6(1)f!7+>MHrL;L`w@vTj=B6nr0CH...
              └ <jumpscale.god.J object at 0x7fb1ecce4b70>

  File "/home/maged/Code/js-ng/jumpscale/sals/zos/network.py", line 57, in create
    network.workload_id = _next_workload_id(reservation)
    │       │             │                 └ TfgridWorkloadsReservation1(_Base__instance_name=None, _Base__parent=None, __metadata='IC`}9$^Cl6(1)f!7+>MHrL;L`w@vTj=B6nr0CH...
    │       │             └ <function _next_workload_id at 0x7fb1e4108620>
    │       └ <property object at 0x7fb1e8f2bd18>
    └ TfgridWorkloadsReservationNetwork1(_Base__instance_name=None, _Base__parent=None, _factories={})

  File "/home/maged/Code/js-ng/jumpscale/sals/zos/id.py", line 20, in _next_workload_id
    for workload in getattr(reservation.data_reservation, _type):
                            │           │                 └ 'zdbs'
                            │           └ <property object at 0x7fb1e8ec9318>
                            └ TfgridWorkloadsReservation1(_Base__instance_name=None, _Base__parent=None, __metadata='IC`}9$^Cl6(1)f!7+>MHrL;L`w@vTj=B6nr0CH...

  File "/home/maged/Code/js-ng/jumpscale/core/base/meta.py", line 123, in getter
    setattr(self, name, default)
            │     │     └ TfgridWorkloadsReservationData1(_Base__instance_name=None, _Base__parent=None, __description='', _factories={})
            │     └ 'data_reservation'
            └ TfgridWorkloadsReservation1(_Base__instance_name=None, _Base__parent=None, __metadata='IC`}9$^Cl6(1)f!7+>MHrL;L`w@vTj=B6nr0CH...

  File "/home/maged/Code/js-ng/jumpscale/core/base/meta.py", line 149, in setter
    field.validate(value)
    │     │        └ TfgridWorkloadsReservationData1(_Base__instance_name=None, _Base__parent=None, __description='', _factories={})
    │     └ <function Object.validate at 0x7fb1e8fcdea0>
    └ <jumpscale.core.base.fields.Object object at 0x7fb1e8f43518>

  File "/home/maged/Code/js-ng/jumpscale/core/base/fields.py", line 358, in validate
    value.validate()
    │     └ <function Base.validate at 0x7fb1e8fd50d0>
    └ TfgridWorkloadsReservationData1(_Base__instance_name=None, _Base__parent=None, __description='', _factories={})

  File "/home/maged/Code/js-ng/jumpscale/core/base/meta.py", line 365, in validate
    field.validate(getattr(self, name))
    │     │                │     └ 'signing_request_provision'
    │     │                └ TfgridWorkloadsReservationData1(_Base__instance_name=None, _Base__parent=None, __description='', _factories={})
    │     └ <function Object.validate at 0x7fb1e8fcdea0>
    └ <jumpscale.core.base.fields.Object object at 0x7fb1e8f31be0>

  File "/home/maged/Code/js-ng/jumpscale/core/base/meta.py", line 123, in getter
    setattr(self, name, default)
            │     │     └ TfgridWorkloadsReservationSigningRequest1(_Base__instance_name=None, _Base__parent=None, __quorum_min=0, __signers=[], _facto...
            │     └ 'signing_request_provision'
            └ TfgridWorkloadsReservationData1(_Base__instance_name=None, _Base__parent=None, __description='', _factories={})

  File "/home/maged/Code/js-ng/jumpscale/core/base/meta.py", line 153, in setter
    value.parent = self
    │     │        └ TfgridWorkloadsReservationData1(_Base__instance_name=None, _Base__parent=None, __description='', _factories={})
    │     └ <property object at 0x7fb1e9081cc8>
    └ TfgridWorkloadsReservationSigningRequest1(_Base__instance_name=None, _Base__parent=None, __quorum_min=0, __signers=[], _facto...

AttributeError: can't set attribute

```

**Comment by m-motawea** [comment]
commit: https://github.com/js-next/js-ng/commit/677171f5f16513b8760b0978089c33f9f4643d3e
