### ISSUE TITLE
error with build sdk ubuntu 20.04

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/js-ng#399]
```
~/js-ng$ poetry install;
~/js-ng$ poetry shell;
~/js-ng$ pip3 install pyinstaller
:~/js-ng$ pyinstaller threesdk.spec
~/js-ng$ cd /home/osboxes/js-ng/dist

~/js-ng/dist$ ./3sdk --help
Traceback (most recent call last):
  File "jumpscale/entry_points/usershell.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/threesdk/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/threesdk/threebot.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/threesdk/identitymanager.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/osboxes/.cache/pypoetry/virtualenvs/js-ng-2KNq7yVu-py3.8/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "jumpscale/loader.py", line 92, in <module>
  File "jumpscale/loader.py", line 66, in expose_all
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEI1yTmjE/jumpscale'
[61648] Failed to execute script usershell


```

- js-ng 

```
commit b6a721c947351d31c1d3ce0ac555ba1903646364 (HEAD -> development, origin/development, origin/HEAD)
Author: Abdelrahman Ghanem <abom.jdev@gmail.com>
Date:   Sun Jul 5 12:39:29 2020 +0200

    remove the old loader

```

**Comment by Pishoy** [comment]
also tried 
```
~/js-ng$ staticx dist/3sdk  3sdk.static
	not a dynamic executable
WARNING:root:Unexpected ldd error (1): 
WARNING:root:Unexpected ldd error (1): /tmp/staticx-pyi-sk8391h9/PIL/_imagingft.cpython-38-x86_64-linux-gnu.so: error while loading shared libraries: libfreetype-69f25d5e.so.6.17.1: ELF load command address/offset not properly aligned

	not a dynamic executable
WARNING:root:Unexpected ldd error (1): 
	not a dynamic executable
WARNING:root:Unexpected ldd error (1): 
	not a dynamic executable
WARNING:root:Unexpected ldd error (1): 

```
