### ISSUE TITLE
network chatflow always crash at start

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/js-ng#409]
I can't start the network chatflow, it immediately crashs.
The threebot server logs shows this error: 
```python
2020-07-08 16:21:20.122 | ERROR    | jumpscale.sals.chatflows.chatflows:wrapper:150 - error
Traceback (most recent call last):

> File "/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 143, in wrapper
    getattr(self, step_name)()
            │     └ 'ubuntu_start'
            └ <tfgrid_solutions.chats.ubuntu_deploy.UbuntuDeploy object at 0x7fc60c20dfa0>

  File "/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/sals/chatflows/chatflows.py", line 624, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ (<tfgrid_solutions.chats.ubuntu_deploy.UbuntuDeploy object at 0x7fc60c20dfa0>,)
           └ <function UbuntuDeploy.ubuntu_start at 0x7fc60c6f0820>

  File "/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/packages/tfgrid_solutions/chats/ubuntu_deploy.py", line 39, in ubuntu_start
    j.sals.reservation_chatflow.validate_user(user_info)
    │ │                                       └ {'username': 'zaibon.3bot', 'email': 'christophe@threefold.tech'}
    │ └ <property object at 0x7fc61246c310>
    └ <jumpscale.loader.J object at 0x7fc61244db80>

  File "/home/zaibon/.cache/pypoetry/virtualenvs/js-ng-1E86Bdzo-py3.8/src/js-ng/jumpscale/loader.py", line 46, in getter
    new_module = mod.export_module_as()
                 │   └ <function export_module_as at 0x7fc60e1aae50>
                 └ <module 'jumpscale.sals.reservation_chatflow' from '/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/sals/rese...

  File "/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/__init__.py", line 4, in export_module_as
    return ReservationChatflow()
           └ <class 'jumpscale.sals.reservation_chatflow.reservation_chatflow.ReservationChatflow'>

  File "/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 221, in __init__
    self.update_local_reservations()
    │    └ <function ReservationChatflow.update_local_reservations at 0x7fc60c29a8b0>
    └ <jumpscale.sals.reservation_chatflow.reservation_chatflow.ReservationChatflow object at 0x7fc60c1e1640>

  File "/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 490, in update_local_reservations
    reservations = self.get_solutions_explorer()
                   │    └ <function ReservationChatflow.get_solutions_explorer at 0x7fc60c29a820>
                   └ <jumpscale.sals.reservation_chatflow.reservation_chatflow.ReservationChatflow object at 0x7fc60c1e1640>

  File "/home/zaibon/dev/gig/code/github/threefoldtech/js-sdk/jumpscale/sals/reservation_chatflow/reservation_chatflow.py", line 441, in get_solutions_explorer
    info = metadata["form_info"]
    │      └ {'Solution name': 'minio hercule demo'}
    └ {}

KeyError: 'form_info'

```

**Comment by BolaNasr** [comment]
Verified
![image](https://user-images.githubusercontent.com/10259267/87242991-21a39900-c432-11ea-9a79-9b87e9baed82.png)

**Comment by xmonader** [comment]
reopening this, probably in the chatflow SAL we make assumption some certain keys exists and it's only created via the admin panel. e.g form_info, these situations needs to be properly handled.

**Comment by dmahmouali** [comment]
related to : https://github.com/threefoldtech/js-sdk/issues/230

**Comment by ashraffouda** [comment]
verifying
