### ISSUE TITLE
find_many raises exception when the base is empty

### ISSUE THREAD

**Issue by m-motawea** [threefoldtech/js-ng#429]
I used find_many on an empty base. it raised exception. shouldn't it return empty results instead?

```python
JS-NG> from jumpscale.sals.marketplace.models import UserPool                                            
JS-NG> from jumpscale.core.base import StoredFactory                                                     
JS-NG> pool_factory = StoredFactory(UserPool)                                                            
JS-NG> pool_factory.find_many(owner="test")                                                              
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maged/.cache/pypoetry/virtualenvs/js-sdk-IZdTbuKY-py3.6/src/js-ng/jumpscale/core/base/factory.py", line 558, in find_many
    new_cursor, count, result = self.store.find(cursor_=cursor_, limit_=limit_, **query)
                                │                       │               │         └ {'owner': 'test'}
                                │                       │               └ None
                                │                       └ None
                                └ <jumpscale.core.base.factory.jumpscalesalsmarketplacemodelsUserPool object at 0x7fb83e510fd0>
ValueError: not enough values to unpack (expected 3, got 2)

not enough values to unpack (expected 3, got 2)
JS-NG>
```

**Comment by abom** [comment]
https://github.com/threefoldtech/js-ng/commit/4ed9788faf2b1070bd5cb0a0f1c49527005f1517

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
