### ISSUE TITLE
local.execute asynchronous execution fail

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/js-ng#568]
### Description

asynchronous execution fails, when exectute a command and set asynchronous to True.

this bug is related to invoke framework, here is the open issue for that bug in pyinvoke repo
https://github.com/pyinvoke/invoke/issues/742

### Steps to reproduce

```
>>> from jumpscale.core.executors import local
>>> local.execute(['sleep', '1'], asynchronous=True)
```

### Traceback/Logs/Alerts

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sameh/projects/js-ng/jumpscale/core/executors/command_builder.py", line 28, in inner
    return func(cmd, *args, **kwargs)
  File "/home/sameh/projects/js-ng/jumpscale/core/executors/local.py", line 160, in execute
    return res.return_code, res.stdout, res.stderr
  File "/home/sameh/projects/js-ng/.venv/lib/python3.8/site-packages/invoke/runners.py", line 1432, in return_code
    return self.exited
AttributeError: 'Promise' object has no attribute 'exited'
```

**Comment by xmonader** [comment]
We can create a PR upstream, but nothing we can do here
