### ISSUE TITLE
can't generate docs with make docs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/js-ng#84]
```
js-ng git:(development) make docs
pdoc3 jumpscale --html --output-dir docs/api --overwrite
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/cli.py:370: DeprecationWarning: Program option `--overwrite` is deprecated. Use `--force`.
  _warn_deprecated('--overwrite', '--force')
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/invoke/loader.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/common.py:233: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class TmuxMappingObject(collections.MutableMapping):
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py:223: UserWarning: Couldn't get/parse source of '<Class 'jumpscale.core.base.meta.FactoryInfo'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
<unknown>:377: DeprecationWarning: invalid escape sequence \ 
<unknown>:567: DeprecationWarning: invalid escape sequence \.
<unknown>:583: DeprecationWarning: invalid escape sequence \d
<unknown>:322: DeprecationWarning: invalid escape sequence \s
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py:223: UserWarning: Couldn't get/parse source of '<Module 'jumpscale.sals.process.process'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
Traceback (most recent call last):
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/bin/pdoc3", line 11, in <module>
    load_entry_point('pdoc3==0.6.3', 'console_scripts', 'pdoc3')()
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/cli.py", line 442, in main
    for module in args.modules]
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/cli.py", line 442, in <listcomp>
    for module in args.modules]
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py", line 605, in __init__
    context=self._context)
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py", line 603, in __init__
    self.doc[root] = m = Module(import_module(fullname),
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py", line 187, in import_module
    assert inspect.ismodule(module)
AssertionError
Makefile:7: recipe for target 'docs' failed
make: *** [docs] Error 1
➜  js-ng git:(development) code .
➜  js-ng git:(development) 

```

**Comment by xmonader** [comment]
more 

```
js-ng git:(development) make docs 
pdoc3 jumpscale --html --output-dir docs/api --overwrite
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/cli.py:370: DeprecationWarning: Program option `--overwrite` is deprecated. Use `--force`.
  _warn_deprecated('--overwrite', '--force')
module:  jumpscale
module:  jumpscale.core
module:  jumpscale.core.config
module:  jumpscale.core.config.config
module:  jumpscale.core.exceptions
module:  jumpscale.core.exceptions.exceptions
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/invoke/loader.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/libtmux/common.py:233: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class TmuxMappingObject(collections.MutableMapping):
module:  jumpscale.core.executors
module:  jumpscale.core.executors.command_builder
module:  jumpscale.core.executors.local
module:  jumpscale.core.executors.remote
module:  jumpscale.core.executors.tmux
module:  jumpscale.core.logging
module:  jumpscale.core.logging.logging
module:  jumpscale.core.base
module:  jumpscale.core.base.factory
module:  jumpscale.core.base.fields
module:  jumpscale.core.base.meta
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py:223: UserWarning: Couldn't get/parse source of '<Class 'jumpscale.core.base.meta.FactoryInfo'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
module:  jumpscale.core.base.store
module:  jumpscale.sals
module:  jumpscale.sals.fs
module:  jumpscale.sals.fs.fs
<unknown>:377: DeprecationWarning: invalid escape sequence \ 
<unknown>:567: DeprecationWarning: invalid escape sequence \.
<unknown>:583: DeprecationWarning: invalid escape sequence \d
module:  jumpscale.sals.hostsfile
module:  jumpscale.sals.hostsfile.hostsfile
module:  jumpscale.sals.process
<unknown>:322: DeprecationWarning: invalid escape sequence \s
module:  jumpscale.sals.process.process
/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py:223: UserWarning: Couldn't get/parse source of '<Module 'jumpscale.sals.process.process'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
module:  jumpscale.data
module:  jumpscale.data.idgenerator
module:  jumpscale.data.idgenerator.idgenerator
module:  jumpscale.data.serializers
module:  jumpscale.data.serializers.base64
module:  jumpscale.data.serializers.json
module:  jumpscale.data.serializers.lzma
module:  jumpscale.data.serializers.msgpack
module:  jumpscale.data.serializers.pickle
module:  jumpscale.data.serializers.toml
module:  jumpscale.data.serializers.yaml
module:  jumpscale.data.hash
module:  jumpscale.data.hash.hash
module:  jumpscale.data.inifile
module:  jumpscale.data.inifile.inifile
module:  jumpscale.data.randomnames
module:  jumpscale.data.randomnames.generate
module:  jumpscale.data.treemanager
module:  jumpscale.data.treemanager.exceptions
module:  jumpscale.data.treemanager.treemanager
module:  jumpscale.data.time
module:  jumpscale.data.terminaltable
module:  jumpscale.data.terminaltable.terminaltable
module:  jumpscale.data.fake
Traceback (most recent call last):
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/bin/pdoc3", line 11, in <module>
    load_entry_point('pdoc3==0.6.3', 'console_scripts', 'pdoc3')()
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/cli.py", line 442, in main
    for module in args.modules]
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/cli.py", line 442, in <listcomp>
    for module in args.modules]
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py", line 605, in __init__
    context=self._context)
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py", line 603, in __init__
    self.doc[root] = m = Module(import_module(fullname),
  File "/home/xmonader/.cache/pypoetry/virtualenvs/js-ng-py3.7/lib/python3.7/site-packages/pdoc/__init__.py", line 187, in import_module
    assert inspect.ismodule(module)
AssertionError
Makefile:7: recipe for target 'docs' failed
make: *** [docs] Error 1

```
it's the way we use fakelib

**Comment by Pishoy** [comment]
am still getting below error with ubuntu 20.4  container 

```

root@62dde2fe8d2b:~/js-ng# poetry install
Installing dependencies from lock file

No dependencies to install or update

  - Installing js-ng (0.1.0)
root@62dde2fe8d2b:~/js-ng# poetry shell
Spawning shell within /root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8
root@62dde2fe8d2b:~/js-ng# . /root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/bin/activate
(js-ng-JVcG1psT-py3.8) root@62dde2fe8d2b:~/js-ng# 
(js-ng-JVcG1psT-py3.8) root@62dde2fe8d2b:~/js-ng# 
(js-ng-JVcG1psT-py3.8) root@62dde2fe8d2b:~/js-ng# make docs
pdoc3 jumpscale --html --output-dir docs/api --force
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/lib/python3.8/site-packages/pdoc/__init__.py", line 183, in import_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/js-ng/jumpscale/install/codeserver-install.py", line 2, in <module>
    from jumpscale.servers.threebot.threebot import ThreebotServer
ModuleNotFoundError: No module named 'jumpscale.servers.threebot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/bin/pdoc3", line 11, in <module>
    load_entry_point('pdoc3==0.6.4', 'console_scripts', 'pdoc3')()
  File "/root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/lib/python3.8/site-packages/pdoc/cli.py", line 448, in main
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "/root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/lib/python3.8/site-packages/pdoc/cli.py", line 448, in <listcomp>
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "/root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/lib/python3.8/site-packages/pdoc/__init__.py", line 602, in __init__
    self.doc[root] = m = Module(import_module(fullname),
  File "/root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/lib/python3.8/site-packages/pdoc/__init__.py", line 602, in __init__
    self.doc[root] = m = Module(import_module(fullname),
  File "/root/.cache/pypoetry/virtualenvs/js-ng-JVcG1psT-py3.8/lib/python3.8/site-packages/pdoc/__init__.py", line 185, in import_module
    raise ImportError('Error importing {!r}: {}'.format(module, e))
ImportError: Error importing 'jumpscale.install.codeserver-install': No module named 'jumpscale.servers.threebot'
make: *** [Makefile:9: api_docs] Error 1
(js-ng-JVcG1psT-py3.8) root@62dde2fe8d2b:~/js-ng# 
(js-ng-JVcG1psT-py3.8) root@62dde2fe8d2b:~/js-ng# 

```

**Comment by xmonader** [comment]
codeserver-install should move to js-sdk repo
